name: "SiteWatchDog"
description: "Check the status of a list of websites and writes the results to the README.md file in your repository."
author: "Quentin JOLY"
branding:
  icon: 'file-text'
  color: 'blue'
inputs:
  README_TEMPLATE_PATH:
    description: "Path to the README template"
    default: "./README.md.tmpl"
  SITES_YAML_PATH:
    description: "Path to the sites.yaml"
    default: "./sites.yaml"
runs:
  using: "docker"
  image: "Dockerfile"
