name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Self run
        uses: qjoly/SiteWatchdog@main

      - name: Check If file are modified
        run: |
          ls -lah
          cat README.md

      # - name: Check outputs
      #   run: |
      #     test "${{ steps.selftest.outputs.myOutput }}" == "Hello world"
