name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Set up Go 1.20
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'
      - name: Run go test
        run: go test -v ./...
